require "config.options"
require "config.keymaps"
require "config.plugins"
require "config.colorscheme"
require "config.vim-tree"
require "config.autopairs"
require "config.lsp"
require "config.dap"
require "config.telescope"
require "config.treesitter"
require "config.neotest"
require "config.copilot"
require "config.bufferline"

vim.api.nvim_set_keymap("n", "<leader>f", ":lua require('config.black').black_format()<CR>", {noremap = true, silent = true})
